# 最新のUbuntuバージョンを指定
FROM ubuntu:22.04

# 必要なツールのインストール
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    wget \
    git \
    tzdata \
    && apt-get clean

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
&& apt-get install -y nodejs

# open port 5173
EXPOSE 5173