name: UnitTest

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Set up Nodejs
        uses: actions/setup-go@v2
        with:
          node-version: "16"

      - name: Build Docker image
        run: docker build -t unittest .

      - name: Run tests inside Docker container and Unittest
        run: |
          docker run --rm -v ${{ github.workspace }}:/client --name unittest unittest /bin/bash -c "\
            cd /client && \
            npm install -g n && \
            npm install -g @vue/cli && \
            echo "================= test start ================= && \
            npm run test -- --coverage && \
            echo "================= test end ================="
